### PR TITLE
Port forwards

### PR DESCRIPTION
**Pull request by kennethgillen**
Do we want to add port forwarding to the example Vagrantfile? 

Seems to make sense that a user would like to fire up a browser and connect, then upload test images once they've provisioned the machine.

cc @joshmoore @manics

### CODE REVIEW

**Comment by joshmoore** [comment]
No immediate objection. We may want to make this optional somehow though, since often those ports won't be free on one of our machines.

**Comment by kennethgillen** [comment]
@joshmoore  - yeah, true: good point. Fundamentally I'm always thinking 'clean machine' but you're right: that's not always the case. I wonder if Vagrant can do 'next-nearest free port'.

**Comment by joshmoore** [comment]
https://www.vagrantup.com/docs/networking/forwarded_ports.html

```
Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 80, host: 8080,
    auto_correct: true
end
```

**Comment by joshmoore** [comment]
Merging before we start to split up into multiple repositories ( see https://github.com/ome/docker-example-omero-websockets/pull/1 )

**Pull request merged**
