### PR TITLE
websockets: add new addition for OMERO 5.5

### PR DESCRIPTION
**Pull request by joshmoore**
This new repository shows how to make use of the experimental
Ice websockets support added in 5.5. The repository itself
also functions as the integration test and the documentation
for the feature.

see:
 - https://github.com/ome/prod-playbooks/pull/167
 - https://github.com/ome/ome-documentation/pull/1963
 - https://github.com/openmicroscopy/openmicroscopy/pull/5927
 - https://github.com/openmicroscopy/openmicroscopy/pull/5997
 - https://github.com/openmicroscopy/openmicroscopy/pull/5998

### CODE REVIEW

**Comment by joshmoore** [comment]
Ah, molecule 1 --> 2. However, there's also an issue of whether this repo shouldn't drop travis if each individual repo is handling it. cc: @sbesson @manics

**Comment by sbesson** [comment]
There is certainly a duplication problem. From my side, the main advantage of top-level Travis is mostly to address scalability issue in two particular cases:

1- setting up cron jobs for all playbooks/roles
2- testing infrastructure changes e.g. new version of Ansible via a single PR rather than n

**Comment by joshmoore** [comment]
All agreed. And thinking about it, this repo won't trigger _per PR_ so the overhead is minimal. We do however need to get everything on the same molecule version:  https://travis-ci.org/ome/omero-deployment-examples/jobs/539677564

Do you guys see that as being doable in time to get this PR merged for 5.5? Or shall I disable travis for the moment, and we'll re-enable when everything is updated?

cc: @manics

**Comment by sbesson** [comment]
With #16 this needs an extra commit to resolve the conflict. Looking at Travis, I am a bit confused as I thought it was a molecule issue from https://github.com/ome/omero-deployment-examples/pull/15#issuecomment-497705948. Isn't the problem rather related to the fact that Travis tries to run `molecule test` while this is adding a Docker-only repo?

Immediately, I think only running the top-level Travis on Ansible repositories/directories is completely fine.

**Comment by joshmoore** [comment]
Conflict fixed & travis disabled. :+1: for getting this in for 5.5.0.

**Pull request merged**
